version: "0.1"
vscode:
    image: codercom/code-server:3.4.1
    volumes:
        - ./home:/home
    command: sudo apt install python python-pip git -y
    ports:
      - "8443:8080"
      - "443:443"
    restart: always